version: "v3.0"
name: UI Continious Monitoring
semaphore_image: standard
blocks:
  - name: "Stage A"
    build:
      jobs:
        - name: Pipeline Page
          commands:
            - "export SEMAPHORE_CACHE_DIR=/tmp"
            - "curl -L https://gist.githubusercontent.com/ervinb/84ddaf56640059f25d18/raw/b2116de1d968d73e082545c4114317e345f93b3f/firefox-semaphore.sh | bash -s 56.0"
            - checkout
            - cd ~/ui-continuous-monitoring
            - ./run
