version: "v3.0"
name: UI Continious Monitoring
semaphore_image: standard
blocks:
  - name: "Stage A"
    build:
      env_vars:
      - name: SESSION_COOKIE_VALUE
        value: BAh7CUkiD3Nlc3Npb25faWQGOgZFVEkiJTAyZjE5ODAyZTExOWFlNzkxNzI0ODA1ODE0ZDJkMTE3BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMXEvNnUwZytBWVVxa0xRNVZZdzgwa2NNVExYZ1NsV1VKS2pGWTRzMUdXVFU9BjsARkkiGXdhcmRlbi51c2VyLnVzZXIua2V5BjsAVFsHWwZJIikzNjlhOTk2NC02NjViLTQyM2ItYTY0My01ZmI0MDYwM2MyNGIGOwBUSSIiJDJhJDEwJDFadHZkUWQvR09rcDR5TnUwbndCTU8GOwBUSSIVc3VwcG9ydF9yZWZlcnJlcgY7AEYiIGh0dHBzOi8vaWQuc2VtYXBob3JlY2kuY29tLw%3D%3D--8439c6e480a11340c11b0a6cf46562295eb6e9b5
      - name: ORGANIZATION_USERNAME
        value: semaphore
      jobs:
        - name: Pipeline Page
          commands:
            - "export SEMAPHORE_CACHE_DIR=/tmp"
            - "curl -L https://gist.githubusercontent.com/ervinb/84ddaf56640059f25d18/raw/b2116de1d968d73e082545c4114317e345f93b3f/firefox-semaphore.sh | bash -s 56.0"
            - checkout && cd ~/cont-monitoring
            - ./run
