#!/usr/bin/env bash

export SESSION_COOKIE_NAME="_semaphoreci_2_0_prod_session"

if [ -z $SESSION_COOKIE ]; then
  echo "SESSION_COOKIE_NAME is not exported"
  exit 1
fi

#
# Follow live log in the background
#
bash src/live_log.sh &
sleep 10

#
# Open important pages continuosly
#

while true; do
  # Generate output
  bash src/generate_output.sh

  # Visit pages
  bash src/id_page.sh
  bash src/me_pages.sh
  bash src/new_org_page.sh
  bash src/home_page.sh
  bash src/org_page.sh
  bash src/dashboard_page.sh
  bash src/project_pages.sh
  bash src/people_page.sh
  bash src/branch_page.sh
  bash src/workflows_page.sh
  bash src/job_page.sh

  sleep 60
done
