#!/usr/bin/env bash

export SESSION_COOKIE_NAME="_semaphoreci_2_0_prod_session"

if [ -z $SESSION_COOKIE_VALUE ]; then
  echo "SESSION_COOKIE_NAME is not exported"
  exit 1
fi

#
# Setting up Firefox cookies.
#

echo "Initializing Firefox cookie DB"
timeout 5 firefox https://google.com || true

echo "Inject session cookie into Firefox cookie DB"
sqlite3 ~/.mozilla/firefox/*.default/cookies.sqlite 'insert into moz_cookies (expiry, baseDomain, host, name, value) values (1517871990791021, "semaphoreci.com", "id.semaphoreci.com", "_semaphoreci_2_0_prod_session", "'$SESSION_COOKIE_VALUE'")'

#
# Follow live log in the background
#
bash live_log.sh &

#
# Open important pages continuosly
#

while true; do
  # Generate some random output on the Job Page
  echo -e "Random output with some colors \e[31mRED\e[0m \e[32mGREEN\e[0m"
  echo -e "newlines"
  echo -e "  indentations"
  echo -e "and some weird Japanese characters. ありがとうございます"
  echo -ne '#####                     (33%)\r'
  sleep 1
  echo -ne '#############             (66%)\r'
  sleep 1
  echo -ne '#######################   (100%)\r'
  echo -ne '\n'

  bash job_page.sh
  bash pipeline_page.sh
  bash branch_page.sh
done

